name: acft_calculator
description: A new Flutter application.
version: 2.0.2

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.12.0
  cloud_functions: ^4.0.10
  cupertino_icons: ^1.0.5
  firebase_analytics: ^10.1.3
  firebase_core: ^2.6.1
  firebase_crashlytics: ^3.0.14
  firebase_performance: ^0.9.0+13
  flutter_riverpod: ^2.2.0
  fluttertoast: ^8.1.3
  google_mobile_ads: ^2.3.0
  in_app_purchase: ^3.1.4
  intl: ^0.17.0
  launch_review: ^3.0.1
  open_file: ^3.2.1
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  pull_down_button: ^0.5.1
  rate_my_app: ^1.1.3
  shared_preferences: ^2.0.15
  sqflite: ^2.2.2
  syncfusion_flutter_pdf: ^20.4.50
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/documents/da_form_705_acft.pdf
    - assets/documents/da_form_705.pdf
    - assets/documents/da_form_5500.pdf
    - assets/documents/da_form_5501.pdf
    - assets/mdl_images/120_pounds.png
    - assets/mdl_images/130_pounds.png
    - assets/mdl_images/140_pounds.png
    - assets/mdl_images/150_pounds.png
    - assets/mdl_images/160_pounds.png
    - assets/mdl_images/170_pounds.png
    - assets/mdl_images/180_pounds.png
    - assets/mdl_images/190_pounds.png
    - assets/mdl_images/200_pounds.png
    - assets/mdl_images/210_pounds.png
    - assets/mdl_images/220_pounds.png
    - assets/mdl_images/230_pounds.png
    - assets/mdl_images/240_pounds.png
    - assets/mdl_images/250_pounds.png
    - assets/mdl_images/260_pounds.png
    - assets/mdl_images/270_pounds.png
    - assets/mdl_images/280_pounds.png
    - assets/mdl_images/290_pounds.png
    - assets/mdl_images/300_pounds.png
    - assets/mdl_images/310_pounds.png
    - assets/mdl_images/320_pounds.png
    - assets/mdl_images/330_pounds.png
    - assets/mdl_images/340_pounds.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
