name: acft_calculator
description: A new Flutter application.
version: 2.2.10

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_functions: ^5.0.4
  cupertino_icons: ^1.0.6
  device_info_plus: ^10.1.2
  firebase_analytics: ^11.2.1
  firebase_core: ^3.3.0
  firebase_crashlytics: ^4.0.4
  firebase_performance: ^0.10.0+4
  fl_chart: ^0.68.0
  flutter_riverpod: ^2.5.1
  fluttertoast: ^8.2.8
  google_mobile_ads: ^5.1.0
  in_app_purchase: ^3.1.13
  intl: ^0.19.0
  launch_review: ^3.0.1
  open_file_plus: ^3.4.1+1
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  pull_down_button: ^0.10.1
  rate_my_app: ^2.2.0
  shared_preferences: ^2.2.3
  sqflite: ^2.3.2
  syncfusion_flutter_pdf: ^26.2.10
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/documents/da_form_705_acft.pdf
    - assets/documents/da_form_705.pdf
    - assets/documents/da_form_5500.pdf
    - assets/documents/da_form_5501.pdf
    - assets/mdl_images/120_pounds.png
    - assets/mdl_images/130_pounds.png
    - assets/mdl_images/140_pounds.png
    - assets/mdl_images/150_pounds.png
    - assets/mdl_images/160_pounds.png
    - assets/mdl_images/170_pounds.png
    - assets/mdl_images/180_pounds.png
    - assets/mdl_images/190_pounds.png
    - assets/mdl_images/200_pounds.png
    - assets/mdl_images/210_pounds.png
    - assets/mdl_images/220_pounds.png
    - assets/mdl_images/230_pounds.png
    - assets/mdl_images/240_pounds.png
    - assets/mdl_images/250_pounds.png
    - assets/mdl_images/260_pounds.png
    - assets/mdl_images/270_pounds.png
    - assets/mdl_images/280_pounds.png
    - assets/mdl_images/290_pounds.png
    - assets/mdl_images/300_pounds.png
    - assets/mdl_images/310_pounds.png
    - assets/mdl_images/320_pounds.png
    - assets/mdl_images/330_pounds.png
    - assets/mdl_images/340_pounds.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
