name: acft_calculator
description: A new Flutter application.

version: 1.3.1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.6
  launch_review: ^3.0.1
  sqflite: ^2.2.0+3
  path_provider: ^2.0.11
  intl: ^0.17.0
  permission_handler: ^10.0.2
  firebase_core: ^2.1.1
  firebase_analytics: ^10.0.4
  cloud_functions: ^4.0.3
  google_mobile_ads: ^2.2.0
  in_app_purchase: ^3.0.8
  charts_flutter: ^0.12.0
  flutter_riverpod: ^2.1.1
  syncfusion_flutter_pdf: ^20.3.52
  open_file: ^3.2.1
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/documents/da_form_705_acft.pdf
    - assets/documents/da_form_705.pdf
    - assets/documents/da_form_5500.pdf
    - assets/documents/da_form_5501.pdf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
